# Generated by Django 2.1.4 on 2019-01-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentname',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentname',
            name='student_id',
        ),
    ]
