# Generated by Django 2.1.4 on 2019-01-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_api', '0003_omrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='is_processed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='omrresult',
            name='image',
            field=models.ImageField(upload_to='resources/omr/images/'),
        ),
    ]
