# Generated by Django 2.1.4 on 2019-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_api', '0004_auto_20190108_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omrresult',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='omrresult',
            name='omr_type',
            field=models.CharField(choices=[('cropped', 'Cropped'), ('full', 'Full')], default='cropped', max_length=15),
        ),
        migrations.AlterField(
            model_name='omrresult',
            name='image',
            field=models.ImageField(upload_to='resources/images/omr'),
        ),
        migrations.AlterField(
            model_name='omrresult',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
