# Generated by Django 2.1.4 on 2019-01-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_api', '0005_auto_20190108_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='question_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='omrresult',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
