# Generated by Django 2.1.4 on 2019-01-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_api', '0006_auto_20190109_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omrresult',
            old_name='image',
            new_name='image_path',
        ),
    ]
