# Generated by Django 4.2 on 2023-04-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_api', '0008_alter_omrresult_id_alter_studentname_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentName',
            new_name='Student',
        ),
    ]
