# Generated by Django 4.2 on 2023-04-16 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drf_file_upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=254, null=True)),
                ('size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file', models.FileField(upload_to=drf_file_upload.models.get_anonymous_uploaded_file_path, validators=[drf_file_upload.models.validate_file_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticatedUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=254, null=True)),
                ('size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file', models.FileField(upload_to=drf_file_upload.models.get_authenticated_uploaded_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
