# Generated by Django 4.2 on 2023-05-03 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import omr_checker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='results/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OMRUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('exam_title', models.CharField(max_length=200)),
                ('section_title', models.CharField(max_length=200)),
                ('subject_title', models.CharField(max_length=200)),
                ('file', models.FileField(storage=omr_checker.models.OverwriteStorage(), upload_to='files/zip', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('roll', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('omr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr_checker.omrresult')),
                ('omr_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr_checker.omrupload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='omrresult',
            name='omr_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr_checker.omrupload'),
        ),
    ]
