# Generated by Django 4.2 on 2023-04-17 05:49

from django.db import migrations, models
import omr_checker.models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrupload',
            name='file',
            field=models.FileField(storage=omr_checker.models.OverwriteStorage(), upload_to=omr_checker.models.get_anonymous_uploaded_file_path, validators=[omr_checker.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
