# Generated by Django 4.2 on 2023-04-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omr_checker', '0002_alter_omrupload_file_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr_checker.exam')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='omr_checker.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
