# Generated by Django 4.2 on 2023-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_checker', '0003_omrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrresult',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
